version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.4.0
  aws-eks: circleci/aws-eks@1.1.0
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          #installing all the dependencies
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install pylint
            make install
      - save_cache:
          paths: #saving of the cache
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: | #performing the lint tests on both of the docker files (green and blue)
            . venv/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            make lint


workflows:
  default:
    jobs:
      - build